# Generated by Django 5.0.7 on 2024-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('электричество', 'Электричество'), ('гибрид', 'Гибрид')], max_length=20)),
                ('transmission', models.CharField(choices=[('механическая', 'Механическая'), ('автоматическая', 'Автоматическая'), ('вариатор', 'Вариатор'), ('робот', 'Робот')], max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
